# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\NOBLEWARRIOR29\Desktop\Open Hymn\primary_screen.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1282, 827)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/source_image/ICO.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(50, 50))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_container = QtWidgets.QFrame(self.centralwidget)
        self.main_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_container.setObjectName("main_container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_container)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_frame = QtWidgets.QFrame(self.main_container)
        self.side_frame.setStyleSheet("#side_frame{\n"
"    background-color: #0e225c;\n"
"}")
        self.side_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.side_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_frame.setObjectName("side_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.side_frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.side_frame)
        self.label.setMinimumSize(QtCore.QSize(66, 122))
        self.label.setStyleSheet("image: url(:/source_image/baptist.PNG);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_5.setStretch(0, 10)
        self.verticalLayout_5.setStretch(1, 68)
        self.horizontalLayout.addWidget(self.side_frame)
        self.main_list_frame = QtWidgets.QFrame(self.main_container)
        self.main_list_frame.setStyleSheet("")
        self.main_list_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_list_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_list_frame.setObjectName("main_list_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_list_frame)
        self.verticalLayout_2.setContentsMargins(20, 40, 0, 30)
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo_label = QtWidgets.QLabel(self.main_list_frame)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.logo_label.setFont(font)
        self.logo_label.setWordWrap(True)
        self.logo_label.setObjectName("logo_label")
        self.verticalLayout_2.addWidget(self.logo_label)
        self.time_label = QtWidgets.QLabel(self.main_list_frame)
        self.time_label.setStyleSheet("#time_label{\n"
"    margin: 6px 0;\n"
"    margin-top: 0;\n"
"}")
        self.time_label.setObjectName("time_label")
        self.verticalLayout_2.addWidget(self.time_label)
        self.search_engine = QtWidgets.QLineEdit(self.main_list_frame)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(16)
        self.search_engine.setFont(font)
        self.search_engine.setStyleSheet("#search_engine{\n"
"    padding: 5px 8px;\n"
"    border: 1px solid rgba(151,154,154,0.1);\n"
"    border-radius: 6px;\n"
"}")
        self.search_engine.setText("")
        self.search_engine.setClearButtonEnabled(True)
        self.search_engine.setObjectName("search_engine")
        self.verticalLayout_2.addWidget(self.search_engine)
        self.song_listwidget = QtWidgets.QListWidget(self.main_list_frame)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.song_listwidget.setFont(font)
        self.song_listwidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.song_listwidget.setStyleSheet("#song_listwidget{\n"
"    border: 1px solid rgba(151,154,154,0.1);\n"
"    background-color: #ffffff;\n"
"    border-radius: 6px;\n"
"}\n"
"#song_listwidget::item{\n"
"    border: 1px solid rgba(151,154,154,0.1);\n"
"    padding: 4px 8px;\n"
"    border-radius: 4px;\n"
"    margin: 0px 2px;\n"
"}\n"
"#song_listwidget::item:selected{\n"
"    border: none;\n"
"    background-color: grey;    \n"
"    color: #ffffff;\n"
"}")
        self.song_listwidget.setObjectName("song_listwidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setKerning(False)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.song_listwidget.addItem(item)
        self.verticalLayout_2.addWidget(self.song_listwidget)
        self.horizontalLayout.addWidget(self.main_list_frame)
        self.main_func_frame = QtWidgets.QFrame(self.main_container)
        self.main_func_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_func_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_func_frame.setObjectName("main_func_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_func_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.song_lyric_frame = QtWidgets.QFrame(self.main_func_frame)
        self.song_lyric_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.song_lyric_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.song_lyric_frame.setObjectName("song_lyric_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.song_lyric_frame)
        self.verticalLayout_4.setContentsMargins(20, 159, 0, 30)
        self.verticalLayout_4.setSpacing(8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.title_label = QtWidgets.QLabel(self.song_lyric_frame)
        self.title_label.setObjectName("title_label")
        self.verticalLayout_4.addWidget(self.title_label)
        self.lyrics_listwidget = QtWidgets.QListWidget(self.song_lyric_frame)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lyrics_listwidget.setFont(font)
        self.lyrics_listwidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lyrics_listwidget.setAutoFillBackground(False)
        self.lyrics_listwidget.setStyleSheet("")
        self.lyrics_listwidget.setFrameShape(QtWidgets.QFrame.Box)
        self.lyrics_listwidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lyrics_listwidget.setLineWidth(1)
        self.lyrics_listwidget.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.lyrics_listwidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.lyrics_listwidget.setMovement(QtWidgets.QListView.Snap)
        self.lyrics_listwidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.lyrics_listwidget.setProperty("isWrapping", False)
        self.lyrics_listwidget.setResizeMode(QtWidgets.QListView.Fixed)
        self.lyrics_listwidget.setViewMode(QtWidgets.QListView.ListMode)
        self.lyrics_listwidget.setWordWrap(True)
        self.lyrics_listwidget.setObjectName("lyrics_listwidget")
        self.verticalLayout_4.addWidget(self.lyrics_listwidget)
        self.horizontalLayout_2.addWidget(self.song_lyric_frame)
        self.live_frame = QtWidgets.QFrame(self.main_func_frame)
        self.live_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.live_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.live_frame.setObjectName("live_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.live_frame)
        self.verticalLayout_3.setContentsMargins(20, 20, 20, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.logo_img = QtWidgets.QLabel(self.live_frame)
        self.logo_img.setStyleSheet("#logo_img{\n"
"    margin-bottom: 147px;\n"
"}")
        self.logo_img.setText("")
        self.logo_img.setObjectName("logo_img")
        self.verticalLayout_3.addWidget(self.logo_img)
        self.label_2 = QtWidgets.QLabel(self.live_frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("#label_2{\n"
"    background-color: #000000;\n"
"    color: rgb(255, 231, 47);\n"
"    padding-right: 70px;\n"
"    padding-left: 50px;\n"
"}")
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.frame_3 = QtWidgets.QFrame(self.live_frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.clear_btn = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.clear_btn.setFont(font)
        self.clear_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clear_btn.setStyleSheet("#clear_btn{\n"
"    color: #ffffff;\n"
"    background-color: grey;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    border-radius: 7px;\n"
"}")
        self.clear_btn.setObjectName("clear_btn")
        self.horizontalLayout_3.addWidget(self.clear_btn)
        self.live_btn = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(14)
        self.live_btn.setFont(font)
        self.live_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.live_btn.setStyleSheet("#live_btn{\n"
"    color: #ffffff;\n"
"    background-color: grey;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    border-radius: 7px;\n"
"}")
        self.live_btn.setObjectName("live_btn")
        self.horizontalLayout_3.addWidget(self.live_btn)
        self.horizontalLayout_3.setStretch(0, 50)
        self.horizontalLayout_3.setStretch(1, 20)
        self.horizontalLayout_3.setStretch(2, 20)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.label_4 = QtWidgets.QLabel(self.live_frame)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.verticalLayout_3.setStretch(0, 10)
        self.verticalLayout_3.setStretch(1, 50)
        self.verticalLayout_3.setStretch(2, 10)
        self.verticalLayout_3.setStretch(3, 10)
        self.horizontalLayout_2.addWidget(self.live_frame)
        self.horizontalLayout_2.setStretch(0, 30)
        self.horizontalLayout_2.setStretch(1, 50)
        self.horizontalLayout.addWidget(self.main_func_frame)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 25)
        self.horizontalLayout.setStretch(2, 70)
        self.verticalLayout.addWidget(self.main_container)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Baptist Favorites"))
        self.logo_label.setText(_translate("MainWindow", "Baptist Favorites"))
        self.time_label.setText(_translate("MainWindow", "TODAY (DATE) GODBLESS US ALL!"))
        self.search_engine.setPlaceholderText(_translate("MainWindow", "Search Hymn..."))
        __sortingEnabled = self.song_listwidget.isSortingEnabled()
        self.song_listwidget.setSortingEnabled(False)
        item = self.song_listwidget.item(0)
        item.setText(_translate("MainWindow", "A New Name in Glory"))
        item = self.song_listwidget.item(1)
        item.setText(_translate("MainWindow", "A Passion for Soul"))
        item = self.song_listwidget.item(2)
        item.setText(_translate("MainWindow", "A Shelter In the Time of Storm"))
        item = self.song_listwidget.item(3)
        item.setText(_translate("MainWindow", "All Hail the Power "))
        item = self.song_listwidget.item(4)
        item.setText(_translate("MainWindow", "Am I Soldier of the Cross"))
        item = self.song_listwidget.item(5)
        item.setText(_translate("MainWindow", "Amazing Grace"))
        item = self.song_listwidget.item(6)
        item.setText(_translate("MainWindow", "Are You Washed in the Blood"))
        item = self.song_listwidget.item(7)
        item.setText(_translate("MainWindow", "At Calvary"))
        item = self.song_listwidget.item(8)
        item.setText(_translate("MainWindow", "At the Cross"))
        item = self.song_listwidget.item(9)
        item.setText(_translate("MainWindow", "Beaulah Land"))
        item = self.song_listwidget.item(10)
        item.setText(_translate("MainWindow", "Blessed Assurance"))
        item = self.song_listwidget.item(11)
        item.setText(_translate("MainWindow", "Blessed be the Name"))
        item = self.song_listwidget.item(12)
        item.setText(_translate("MainWindow", "Bring Them In"))
        item = self.song_listwidget.item(13)
        item.setText(_translate("MainWindow", "Bringing in the Sheaves"))
        item = self.song_listwidget.item(14)
        item.setText(_translate("MainWindow", "Calvary Covers it All"))
        item = self.song_listwidget.item(15)
        item.setText(_translate("MainWindow", "Christ Arose "))
        item = self.song_listwidget.item(16)
        item.setText(_translate("MainWindow", "Christ Liveth in Me"))
        item = self.song_listwidget.item(17)
        item.setText(_translate("MainWindow", "Come Unto Me"))
        item = self.song_listwidget.item(18)
        item.setText(_translate("MainWindow", "Constantly Abiding"))
        item = self.song_listwidget.item(19)
        item.setText(_translate("MainWindow", "Count Your Blessings"))
        item = self.song_listwidget.item(20)
        item.setText(_translate("MainWindow", "Day by Day"))
        item = self.song_listwidget.item(21)
        item.setText(_translate("MainWindow", "Doxology"))
        item = self.song_listwidget.item(22)
        item.setText(_translate("MainWindow", "Dwelling in Beaulah Land"))
        item = self.song_listwidget.item(23)
        item.setText(_translate("MainWindow", "Each Step I Take"))
        item = self.song_listwidget.item(24)
        item.setText(_translate("MainWindow", "Faith is the Victory"))
        item = self.song_listwidget.item(25)
        item.setText(_translate("MainWindow", "Glory to His Name"))
        item = self.song_listwidget.item(26)
        item.setText(_translate("MainWindow", "God will Take Care of You"))
        item = self.song_listwidget.item(27)
        item.setText(_translate("MainWindow", "Grace Greater than Our Sins"))
        item = self.song_listwidget.item(28)
        item.setText(_translate("MainWindow", "Great is Thy Faithfulness"))
        item = self.song_listwidget.item(29)
        item.setText(_translate("MainWindow", "Have Thine Own Way Lord"))
        item = self.song_listwidget.item(30)
        item.setText(_translate("MainWindow", "Have You any Room for Jesus"))
        item = self.song_listwidget.item(31)
        item.setText(_translate("MainWindow", "He Abides"))
        item = self.song_listwidget.item(32)
        item.setText(_translate("MainWindow", "He Hideth My Soul"))
        item = self.song_listwidget.item(33)
        item.setText(_translate("MainWindow", "He Keeps Me Singing"))
        item = self.song_listwidget.item(34)
        item.setText(_translate("MainWindow", "He Leadeth Me"))
        item = self.song_listwidget.item(35)
        item.setText(_translate("MainWindow", "He Lives"))
        item = self.song_listwidget.item(36)
        item.setText(_translate("MainWindow", "Heavenly Sunlight"))
        item = self.song_listwidget.item(37)
        item.setText(_translate("MainWindow", "Higher Ground"))
        item = self.song_listwidget.item(38)
        item.setText(_translate("MainWindow", "Hold the Fort"))
        item = self.song_listwidget.item(39)
        item.setText(_translate("MainWindow", "Holy, Holy, Holy"))
        item = self.song_listwidget.item(40)
        item.setText(_translate("MainWindow", "How Great Thou Art"))
        item = self.song_listwidget.item(41)
        item.setText(_translate("MainWindow", "I Am Resolved"))
        item = self.song_listwidget.item(42)
        item.setText(_translate("MainWindow", "I Am Thine O Lord"))
        item = self.song_listwidget.item(43)
        item.setText(_translate("MainWindow", "I Belong to the King"))
        item = self.song_listwidget.item(44)
        item.setText(_translate("MainWindow", "I Heard the Voice of Jesus Say"))
        item = self.song_listwidget.item(45)
        item.setText(_translate("MainWindow", "I Know Who Holds Tomorrow"))
        item = self.song_listwidget.item(46)
        item.setText(_translate("MainWindow", "I Know Whom I Believed"))
        item = self.song_listwidget.item(47)
        item.setText(_translate("MainWindow", "I Love to Tell the Story"))
        item = self.song_listwidget.item(48)
        item.setText(_translate("MainWindow", "I Need Thee Every Hour"))
        item = self.song_listwidget.item(49)
        item.setText(_translate("MainWindow", "I Shall Not be Moved"))
        item = self.song_listwidget.item(50)
        item.setText(_translate("MainWindow", "I Surrender All"))
        item = self.song_listwidget.item(51)
        item.setText(_translate("MainWindow", "Ill be True, Precious Jesus"))
        item = self.song_listwidget.item(52)
        item.setText(_translate("MainWindow", "Is Your All in the Altar"))
        item = self.song_listwidget.item(53)
        item.setText(_translate("MainWindow", "It is Well with My Soul"))
        item = self.song_listwidget.item(54)
        item.setText(_translate("MainWindow", "Jesus Paid it All"))
        item = self.song_listwidget.item(55)
        item.setText(_translate("MainWindow", "Jesus Saves"))
        item = self.song_listwidget.item(56)
        item.setText(_translate("MainWindow", "Jesus, Lover of My Soul"))
        item = self.song_listwidget.item(57)
        item.setText(_translate("MainWindow", "Joy in Serving Jesus"))
        item = self.song_listwidget.item(58)
        item.setText(_translate("MainWindow", "Just As I Am"))
        item = self.song_listwidget.item(59)
        item.setText(_translate("MainWindow", "Leaning On the Everlasting Arms"))
        item = self.song_listwidget.item(60)
        item.setText(_translate("MainWindow", "Living for Jesus"))
        item = self.song_listwidget.item(61)
        item.setText(_translate("MainWindow", "Love Lifted Me"))
        item = self.song_listwidget.item(62)
        item.setText(_translate("MainWindow", "Loyalty to Christ"))
        item = self.song_listwidget.item(63)
        item.setText(_translate("MainWindow", "Make Me a Blessing"))
        item = self.song_listwidget.item(64)
        item.setText(_translate("MainWindow", "Make Me a Channel of Blessing"))
        item = self.song_listwidget.item(65)
        item.setText(_translate("MainWindow", "Mansion Over The Hilltop"))
        item = self.song_listwidget.item(66)
        item.setText(_translate("MainWindow", "Meet Me There"))
        item = self.song_listwidget.item(67)
        item.setText(_translate("MainWindow", "Mine Eyes Have Seen the Glory"))
        item = self.song_listwidget.item(68)
        item.setText(_translate("MainWindow", "My Father Planned it All"))
        item = self.song_listwidget.item(69)
        item.setText(_translate("MainWindow", "My Savior First of All"))
        item = self.song_listwidget.item(70)
        item.setText(_translate("MainWindow", "My Saviors Love"))
        item = self.song_listwidget.item(71)
        item.setText(_translate("MainWindow", "My Sins are Gone"))
        item = self.song_listwidget.item(72)
        item.setText(_translate("MainWindow", "Near the Cross"))
        item = self.song_listwidget.item(73)
        item.setText(_translate("MainWindow", "Nothing but the Blood of Jesus"))
        item = self.song_listwidget.item(74)
        item.setText(_translate("MainWindow", "Now I Belong to Jesus"))
        item = self.song_listwidget.item(75)
        item.setText(_translate("MainWindow", "Oh How I Love Jesus"))
        item = self.song_listwidget.item(76)
        item.setText(_translate("MainWindow", "One Day"))
        item = self.song_listwidget.item(77)
        item.setText(_translate("MainWindow", "Onward Christian Soldiers"))
        item = self.song_listwidget.item(78)
        item.setText(_translate("MainWindow", "Open My Eyes, That I May See"))
        item = self.song_listwidget.item(79)
        item.setText(_translate("MainWindow", "Our Best"))
        item = self.song_listwidget.item(80)
        item.setText(_translate("MainWindow", "Pass Me Not"))
        item = self.song_listwidget.item(81)
        item.setText(_translate("MainWindow", "Praise Him, Praise Him"))
        item = self.song_listwidget.item(82)
        item.setText(_translate("MainWindow", "Redeemed (F. Crosby)"))
        item = self.song_listwidget.item(83)
        item.setText(_translate("MainWindow", "Rescue the Perishing"))
        item = self.song_listwidget.item(84)
        item.setText(_translate("MainWindow", "Revive Us Again"))
        item = self.song_listwidget.item(85)
        item.setText(_translate("MainWindow", "Rock of Ages"))
        item = self.song_listwidget.item(86)
        item.setText(_translate("MainWindow", "Saved, Saved"))
        item = self.song_listwidget.item(87)
        item.setText(_translate("MainWindow", "Save Through Jesus Blood"))
        item = self.song_listwidget.item(88)
        item.setText(_translate("MainWindow", "Savior Like a Shepherd Lead Us"))
        item = self.song_listwidget.item(89)
        item.setText(_translate("MainWindow", "Send the Light"))
        item = self.song_listwidget.item(90)
        item.setText(_translate("MainWindow", "Shall We Gather at the River"))
        item = self.song_listwidget.item(91)
        item.setText(_translate("MainWindow", "Since Jesus Came into My Heart"))
        item = self.song_listwidget.item(92)
        item.setText(_translate("MainWindow", "Softly and Tenderly"))
        item = self.song_listwidget.item(93)
        item.setText(_translate("MainWindow", "Sound the Battle Cry"))
        item = self.song_listwidget.item(94)
        item.setText(_translate("MainWindow", "Stand Up for Jesus"))
        item = self.song_listwidget.item(95)
        item.setText(_translate("MainWindow", "Standing On the Promises"))
        item = self.song_listwidget.item(96)
        item.setText(_translate("MainWindow", "Stepping In the Light"))
        item = self.song_listwidget.item(97)
        item.setText(_translate("MainWindow", "Still Sweeter Everyday"))
        item = self.song_listwidget.item(98)
        item.setText(_translate("MainWindow", "Such Love"))
        item = self.song_listwidget.item(99)
        item.setText(_translate("MainWindow", "Sweet By and By"))
        item = self.song_listwidget.item(100)
        item.setText(_translate("MainWindow", "Sweet Hour of Prayer"))
        item = self.song_listwidget.item(101)
        item.setText(_translate("MainWindow", "Sweet Peace the Gift of God\'s Love"))
        item = self.song_listwidget.item(102)
        item.setText(_translate("MainWindow", "Tell It to Jesus"))
        item = self.song_listwidget.item(103)
        item.setText(_translate("MainWindow", "The Banner of the Cross"))
        item = self.song_listwidget.item(104)
        item.setText(_translate("MainWindow", "The Bible Stands"))
        item = self.song_listwidget.item(105)
        item.setText(_translate("MainWindow", "The Church\'s One Foundation"))
        item = self.song_listwidget.item(106)
        item.setText(_translate("MainWindow", "The Comforter has Come"))
        item = self.song_listwidget.item(107)
        item.setText(_translate("MainWindow", "The Fight is On"))
        item = self.song_listwidget.item(108)
        item.setText(_translate("MainWindow", "The Lily of the Valley"))
        item = self.song_listwidget.item(109)
        item.setText(_translate("MainWindow", "The Name of Jesus"))
        item = self.song_listwidget.item(110)
        item.setText(_translate("MainWindow", "The Old Rugged Cross"))
        item = self.song_listwidget.item(111)
        item.setText(_translate("MainWindow", "The Regions Beyond"))
        item = self.song_listwidget.item(112)
        item.setText(_translate("MainWindow", "The Solid Rock"))
        item = self.song_listwidget.item(113)
        item.setText(_translate("MainWindow", "There is Power in the Blood"))
        item = self.song_listwidget.item(114)
        item.setText(_translate("MainWindow", "There Shall Be Showers of Blessings"))
        item = self.song_listwidget.item(115)
        item.setText(_translate("MainWindow", "Theres a Great Day Coming"))
        item = self.song_listwidget.item(116)
        item.setText(_translate("MainWindow", "This World is not My Home"))
        item = self.song_listwidget.item(117)
        item.setText(_translate("MainWindow", "Till The Whole World Knows"))
        item = self.song_listwidget.item(118)
        item.setText(_translate("MainWindow", "Tis So Sweet to Trust in Jesus"))
        item = self.song_listwidget.item(119)
        item.setText(_translate("MainWindow", "To God Be the Glory"))
        item = self.song_listwidget.item(120)
        item.setText(_translate("MainWindow", "To the Work"))
        item = self.song_listwidget.item(121)
        item.setText(_translate("MainWindow", "Trust and Obey"))
        item = self.song_listwidget.item(122)
        item.setText(_translate("MainWindow", "Turn Your Eyes Upon Jesus"))
        item = self.song_listwidget.item(123)
        item.setText(_translate("MainWindow", "Verily, Verily"))
        item = self.song_listwidget.item(124)
        item.setText(_translate("MainWindow", "Victory In Jesus"))
        item = self.song_listwidget.item(125)
        item.setText(_translate("MainWindow", "Weve a Story to Tell"))
        item = self.song_listwidget.item(126)
        item.setText(_translate("MainWindow", "What a Friend"))
        item = self.song_listwidget.item(127)
        item.setText(_translate("MainWindow", "When the Roll is Called Up Yonder"))
        item = self.song_listwidget.item(128)
        item.setText(_translate("MainWindow", "When We all Get to Heaven"))
        item = self.song_listwidget.item(129)
        item.setText(_translate("MainWindow", "Where Could I Go"))
        item = self.song_listwidget.item(130)
        item.setText(_translate("MainWindow", "Whisper a Prayer"))
        item = self.song_listwidget.item(131)
        item.setText(_translate("MainWindow", "Who Is on the Lord Side"))
        item = self.song_listwidget.item(132)
        item.setText(_translate("MainWindow", "Wonderful Grace of Jesus"))
        item = self.song_listwidget.item(133)
        item.setText(_translate("MainWindow", "Wonderful Words of Life"))
        item = self.song_listwidget.item(134)
        item.setText(_translate("MainWindow", "Yes, I Know"))
        item = self.song_listwidget.item(135)
        item.setText(_translate("MainWindow", "BASTA\'T TAYO\'Y SAMA-SAMA"))
        item = self.song_listwidget.item(136)
        item.setText(_translate("MainWindow", "FIND US FAITHFUL"))
        item = self.song_listwidget.item(137)
        item.setText(_translate("MainWindow", "HAVE YOU DECIDED TO FOLLOW JESUS"))
        item = self.song_listwidget.item(138)
        item.setText(_translate("MainWindow", "PSALMS 19"))
        self.song_listwidget.setSortingEnabled(__sortingEnabled)
        self.title_label.setText(_translate("MainWindow", "Song: {TITLE}"))
        self.clear_btn.setText(_translate("MainWindow", "CLEAR"))
        self.live_btn.setText(_translate("MainWindow", "Live"))
import image


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
